<?php
$theme_config_setting = array (
    '___site_config___' =>
        array (
            'fieldname' => '___site_config___',
            'alias' => '网站基础设置',
            'diyfield_type' => 'delimiter',
            'field_type' => 'varchar',
            'constraint' => '20',
            'default_status' => '0',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'site_main_logo' =>
        array (
            'fieldname' => 'site_main_logo',
            'alias' => '主LOGO',
            'diyfield_type' => 'single_image',
            'field_type' => 'varchar',
            'constraint' => '100',
            'width' => '5',
            'help' => '【高度：80px】',
            'edit' => '1',
            'parent' => '',
        ),
    'site_sub_logo' =>
        array (
            'fieldname' => 'site_sub_logo',
            'alias' => '页脚LOGO',
            'diyfield_type' => 'single_image',
            'field_type' => 'varchar',
            'constraint' => '100',
            'width' => '5',
            'help' => '【高度：80px】',
            'edit' => '1',
            'parent' => '',
        ),
    'site_favicon' =>
        array (
            'fieldname' => 'site_favicon',
            'alias' => '网站图标',
            'diyfield_type' => 'single_image',
            'field_type' => 'varchar',
            'constraint' => '100',
            'default' => '',
            'width' => '5',
            'help' => '【图标大小64x64】',
            'edit' => '1',
            'parent' => '',
        ),
    'site_header_slogan' =>
        array (
            'fieldname' => 'site_header_slogan',
            'alias' => '网站页头口号',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'language' => '1',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'site_footer_slogan' =>
        array (
            'fieldname' => 'site_footer_slogan',
            'alias' => '网站尾部口号',
            'diyfield_type' => 'editor',
            'field_type' => 'mediumtext',
            'constraint' => '',
            'language' => '1',
            'editor_type' => 'simple',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'site_amp_url' =>
        array (
            'fieldname' => 'site_amp_url',
            'alias' => 'AMP地址',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => 'url',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    '___contact_config___' =>
        array (
            'fieldname' => '___contact_config___',
            'alias' => '公司联系信息',
            'diyfield_type' => 'delimiter',
            'field_type' => 'varchar',
            'constraint' => '20',
            'default_status' => '0',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'home_contact_text' =>
        array (
            'fieldname' => 'home_contact_text',
            'alias' => '联系信息',
            'diyfield_type' => 'editor',
            'field_type' => 'mediumtext',
            'constraint' => '',
            'language' => '1',
            'editor_type' => 'simple',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'com_telephone' =>
        array (
            'fieldname' => 'com_telephone',
            'alias' => '公司电话',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '+86-1234-5678',
            'width' => '5',
            'help' => '【格式：<code>+86-1234-5678</code> 多条信息时：使用 <code>|</code> 分割，例如： <code>Tom:+86-1234-5678|Bob:+86-1234-5678</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    'com_fax' =>
        array (
            'fieldname' => 'com_fax',
            'alias' => '公司传真',
            'diyfield_type' => 'text',
            'default' => '+86-1234-5678',
            'width' => '5',
            'help' => '【格式：<code>+86-1234-5678</code> 多条信息时：使用 <code>|</code> 分割，例如：  <code>Fax1:+86-1234-5678|Fax2:+86-1234-5678</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    'com_email' =>
        array (
            'fieldname' => 'com_email',
            'alias' => '公司邮箱',
            'diyfield_type' => 'text',
            'default' => 'email@domain.com',
            'width' => '5',
            'help' => '【格式：<code>email@domain.com</code> 多条信息时：使用 <code>|</code> 分割，例如：  <code>Tom:email1@domain.com|Bob:email2@domain.com</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    'com_phone' =>
        array (
            'fieldname' => 'com_phone',
            'alias' => '公司手机',
            'diyfield_type' => 'text',
            'default' => '',
            'width' => '5',
            'help' => '【格式：<code>+86-1234-5678</code> 多条信息时：使用 <code>|</code> 分割，例如：  <code>Tom:+86-1234-5678|Bob:+86-1234-5678</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    'com_address' =>
        array (
            'fieldname' => 'com_address',
            'alias' => '公司地址',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => 'Tianan Digital City, Nancheng District, Dongguan, Guangdong Province',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'com_map_marker' =>
        array (
            'fieldname' => 'com_map_marker',
            'alias' => '地图坐标',
            'diyfield_type' => 'text',
            'default' => '22.9882534,113.703565',
            'width' => '5',
            'help' => '【例如：<code>22.9882534,113.703565</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    '___soc_title___' =>
        array (
            'fieldname' => '___soc_title___',
            'alias' => '社交链接',
            'diyfield_type' => 'legend',
            'field_type' => 'varchar',
            'constraint' => '20',
            'remark' => '',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'soc_facebook' =>
        array (
            'fieldname' => 'soc_facebook',
            'alias' => 'Facebook',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【填写平台主页的完整链接】',
            'edit' => '1',
        ),
    'soc_linkedin' =>
        array (
            'fieldname' => 'soc_linkedin',
            'alias' => 'LinkedIn',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【填写平台主页的完整链接】',
            'edit' => '1',
        ),
    'soc_twitter' =>
        array (
            'fieldname' => 'soc_twitter',
            'alias' => 'Twitter',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【填写平台主页的完整链接】',
            'edit' => '1',
        ),
    'soc_youtube' =>
        array (
            'fieldname' => 'soc_youtube',
            'alias' => 'YouTube',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【填写平台主页的完整链接】',
            'edit' => '1',
        ),
    'soc_google' =>
        array (
            'fieldname' => 'soc_google',
            'alias' => 'Google+',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【填写平台主页的完整链接】',
            'edit' => '1',
        ),
    'soc_pinterest' =>
        array (
            'fieldname' => 'soc_pinterest',
            'alias' => 'Pinterest',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【填写平台主页的完整链接】',
            'edit' => '1',
        ),
    '___home_banner_config___' =>
        array (
            'fieldname' => '___home_banner_config___',
            'alias' => '首页Banner设置',
            'diyfield_type' => 'delimiter',
            'field_type' => 'varchar',
            'constraint' => '20',
            'default_status' => '0',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'home_banner' =>
        array (
            'fieldname' => 'home_banner',
            'alias' => '首页Banner',
            'diyfield_type' => 'group',
            'field_type' => 'varchar',
            'constraint' => '20',
            'group_type' => 'fixed',
            'group_num' => '4',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
            'group' =>
                array (
                    'switch' =>
                        array (
                            'fieldname' => 'switch',
                            'alias' => '开关按钮',
                            'diyfield_type' => 'radio',
                            'field_type' => 'varchar',
                            'constraint' => '200',
                            'diydata' =>
                                array (
                                    0 =>
                                        array (
                                            'key' => '开启',
                                            'value' => '1',
                                        ),
                                    1 =>
                                        array (
                                            'key' => '关闭',
                                            'value' => '0',
                                        ),
                                ),
                            'default' => '1',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                    'image' =>
                        array (
                            'fieldname' => 'image',
                            'alias' => '图片',
                            'diyfield_type' => 'single_image',
                            'field_type' => 'varchar',
                            'constraint' => '100',
                            'default' => '',
                            'width' => '5',
                            'help' => '【图片大小1920x600px】',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                    'link' =>
                        array (
                            'fieldname' => 'link',
                            'alias' => '链接',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '【使用站内链接使用相对地址，如：<code>/product/led-1.html</code>】',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                    'title' =>
                        array (
                            'fieldname' => 'title',
                            'alias' => '标题',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                    'sub_title' =>
                        array (
                            'fieldname' => 'sub_title',
                            'alias' => '副标题',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                    'text' =>
                        array (
                            'fieldname' => 'text',
                            'alias' => '文本描述',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                    'align' =>
                        array (
                            'fieldname' => 'align',
                            'alias' => '文字对齐',
                            'diyfield_type' => 'radio',
                            'field_type' => 'varchar',
                            'constraint' => '200',
                            'diydata' =>
                                array (
                                    0 =>
                                        array (
                                            'key' => '左',
                                            'value' => 'left',
                                        ),
                                    1 =>
                                        array (
                                            'key' => '中',
                                            'value' => 'center',
                                        ),
                                    2 =>
                                        array (
                                            'key' => '右',
                                            'value' => 'right',
                                        ),
                                ),
                            'default' => 'left',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_banner',
                        ),
                ),
        ),
    '___home_section_config___' =>
        array (
            'fieldname' => '___home_section_config___',
            'alias' => '首页区域设置',
            'diyfield_type' => 'delimiter',
            'field_type' => 'varchar',
            'constraint' => '20',
            'default_status' => '0',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    '___home_features_title___' =>
        array (
            'fieldname' => '___home_features_title___',
            'alias' => '产品分类特色功能区【features】',
            'diyfield_type' => 'legend',
            'field_type' => 'varchar',
            'constraint' => '20',
            'remark' => '',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'home_products_title' =>
        array (
            'fieldname' => 'home_products_title',
            'alias' => '产品分类大标题',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'language' => '1',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【该字段用作首页的h1，拥有首页<code>最高权重关键词</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    'home_product_introduction' =>
        array (
            'fieldname' => 'home_product_introduction',
            'alias' => '产品分类介绍',
            'diyfield_type' => 'group',
            'field_type' => 'varchar',
            'constraint' => '20',
            'group_num' => '2',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
            'group' =>
                array (
                    'title' =>
                        array (
                            'fieldname' => 'title',
                            'alias' => '标题',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_product_introduction',
                        ),
                    'text' =>
                        array (
                            'fieldname' => 'text',
                            'alias' => '文本描述',
                            'diyfield_type' => 'editor',
                            'field_type' => 'mediumtext',
                            'constraint' => '',
                            'language' => '1',
                            'editor_type' => 'simple',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_product_introduction',
                        ),
                ),
        ),
    'home_features' =>
        array (
            'fieldname' => 'home_features',
            'alias' => '产品分类4大特色',
            'diyfield_type' => 'group',
            'field_type' => 'varchar',
            'constraint' => '20',
            'group_num' => '4',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
            'group' =>
                array (
                    'title' =>
                        array (
                            'fieldname' => 'title',
                            'alias' => '标题',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_features',
                        ),
                    'text' =>
                        array (
                            'fieldname' => 'text',
                            'alias' => '文本描述',
                            'diyfield_type' => 'editor',
                            'field_type' => 'mediumtext',
                            'constraint' => '',
                            'language' => '1',
                            'editor_type' => 'simple',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_features',
                        ),
                ),
        ),
    'home_reason' =>
        array (
            'fieldname' => 'home_reason',
            'alias' => '选择我们的产品的原因',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'language' => '1',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '【格式：<code>Quality products|Full insurance|lifetime warranty|100% satisfaction|Expert installer|Huimin price</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    '___home_video_title___' =>
        array (
            'fieldname' => '___home_video_title___',
            'alias' => '视频介绍【video】',
            'diyfield_type' => 'legend',
            'field_type' => 'varchar',
            'constraint' => '20',
            'remark' => '',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'home_video_title' =>
        array (
            'fieldname' => 'home_video_title',
            'alias' => '视频介绍标题',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'language' => '1',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '文本标题,通过<code>{}</code>提升字体高亮， 比如： ABOUT {COMPANY}',
            'edit' => '1',
            'parent' => '',
        ),
    'home_video_text' =>
        array (
            'fieldname' => 'home_video_text',
            'alias' => '视频介绍文本描述',
            'diyfield_type' => 'editor',
            'field_type' => 'mediumtext',
            'constraint' => '',
            'language' => '1',
            'editor_type' => 'simple',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'home_video_list' =>
        array (
            'fieldname' => 'home_video_list',
            'alias' => '视频介绍特色列表',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'language' => '1',
            'validation' => '',
            'default' => '',
            'width' => '10',
            'help' => '【格式：<code>Leader for custom door and RFID solutions.|Quality, performance & value.|Provide you with a convenient life</code>】',
            'edit' => '1',
            'parent' => '',
        ),
    'home_video_image' =>
        array (
            'fieldname' => 'home_video_image',
            'alias' => '视频介绍封面图',
            'diyfield_type' => 'single_image',
            'field_type' => 'varchar',
            'constraint' => '100',
            'default' => '',
            'width' => '5',
            'help' => '【图片比例 4:3】',
            'edit' => '1',
            'parent' => '',
        ),
    'home_video_link' =>
        array (
            'fieldname' => 'home_video_link',
            'alias' => '视频介绍视频链接',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'validation' => 'url',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'home_video' =>
        array (
            'fieldname' => 'home_video',
            'alias' => '视频介绍特色',
            'diyfield_type' => 'group',
            'field_type' => 'varchar',
            'constraint' => '20',
            'group_num' => '4',
            'default' => '4',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
            'group' =>
                array (
                    'title' =>
                        array (
                            'fieldname' => 'title',
                            'alias' => '标题',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_video',
                        ),
                    'text' =>
                        array (
                            'fieldname' => 'text',
                            'alias' => '文本描述',
                            'diyfield_type' => 'editor',
                            'field_type' => 'mediumtext',
                            'constraint' => '',
                            'language' => '1',
                            'editor_type' => 'all',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'home_video',
                        ),
                ),
        ),
    '__inside_footer_config__' =>
        array(
            'fieldname' => '__inside_footer_config__',
            'alias' => '页脚设置',
            'diyfield_type' => 'delimiter',
            'field_type' => 'varchar',
            'constraint' => '20',
            'default_status' => '0',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'footer_list_title_1' =>
        array (
            'fieldname' => 'footer_list_title_1',
            'alias' => '底部列表标题',
            'diyfield_type' => 'text',
            'field_type' => 'text',
            'constraint' => '',
            'language' => '1',
            'validation' => '',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'footer_list_1' =>
        array (
            'fieldname' => 'footer_list_1',
            'alias' => '底部链接列表',
            'diyfield_type' => 'group',
            'field_type' => 'varchar',
            'constraint' => '20',
            'group_num' => '24',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
            'group' =>
                array (
                    'title' =>
                        array (
                            'fieldname' => 'title',
                            'alias' => '标题',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'footer_list_1',
                        ),
                    'link' =>
                        array (
                            'fieldname' => 'link',
                            'alias' => '链接',
                            'diyfield_type' => 'text',
                            'field_type' => 'text',
                            'constraint' => '',
                            'language' => '1',
                            'validation' => '',
                            'default' => '',
                            'width' => '5',
                            'help' => '',
                            'edit' => '1',
                            'parent' => 'footer_list_1',
                        ),
                ),
        ),
    '__inside_page_config__' =>
        array (
            'fieldname' => '__inside_page_config__',
            'alias' => '内页设置',
            'diyfield_type' => 'delimiter',
            'field_type' => 'varchar',
            'constraint' => '20',
            'default_status' => '0',
            'default' => '',
            'width' => '5',
            'help' => '',
            'edit' => '1',
            'parent' => '',
        ),
    'inside_default_banner' =>
        array (
            'fieldname' => 'inside_default_banner',
            'alias' => '内页默认Banner',
            'diyfield_type' => 'single_image',
            'field_type' => 'varchar',
            'constraint' => '100',
            'default' => '',
            'width' => '5',
            'help' => '【图片尺寸：1920x200px】',
            'edit' => '1',
            'parent' => '',
        ),
);
?>